# Generated by Django 5.2.17 on 2026-09-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL (e.g. Unsplash or CDN)', max_length=500, null=True),
        ),
    ]
